source: .
destination: ./_site
name: "Lean On Tree"
description : "Living, breathing, seeing, observing, existing. Sometimes, we all need to LeanOnTree.It's a story. It's life. Yours and mine."
highlighter: rouge
permalink: none

url: http://leanontree.com
markdown: rdiscount
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
excerpt_separator: <!--more-->
timezone: Asia/Kolkata
defaults:
 -
  scope:
   path: ""
  values:
    layout: "default"
    author: "Punyasloka Parida"
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-octicons
analytics :
  provider : google
  google :
      tracking_id : 'UA-65359714-1'
exclude: ['vendor','build_script', 'Gemfile','Gemfile.lock','README.md','assets/stylesheets/sass','tag/tag_template_generator.py','tag/index.html','localserver.bat','localsass.bat','.travis.yml','*.log', ]
 